### ISSUE TITLE
Solo pool testing

### ISSUE THREAD

**Issue by Tkorrick** [onemorebsmith/kaspa-stratum-bridge#35]
### Discussed in https://github.com/onemorebsmith/kaspa-stratum-bridge/discussions/34

<div type='discussions-op-text'>

<sup>Originally posted by **onemorebsmith** September 26, 2022</sup>
Thread for reporting issues with the solo pool</div>

I keep seeing this error for no miner address. My shares submitted seem to stop and restarting the miner clears it for a short time. Using BZMiner 11.1.0. There are no errors in the miner window on any of the miners. Just no shares being found.
<img width="398" alt="image" src="https://user-images.githubusercontent.com/114526438/192621426-5247c557-fbd0-4050-9cb7-547722c40f6b.png">

**Comment by Tkorrick** [comment]
Follow-up: I still see the occasional err_no_miner_address but I have been running for 30 minutes with shares producing. The only thing I did different was to switch to LOLMINER 1.59a. Great latency time - better than I got over at WoolyPooly.  THANKS FOR THIS WORK!

I will keep you posted as I try and mine for a day and compare to my previous history.

**Comment by onemorebsmith** [comment]
FYI I've found that lol 1.59a has been generating invalid blocks all day, might want to swap to bz miner or srb if possible.

**Comment by Tkorrick** [comment]
Bummer. Thanks. Unfortunately BZminer stops creating shares on your pool for me after 5-10minutes. It keeps mining just no shares.

**Comment by onemorebsmith** [comment]
That issue should have been fixed as of 5 minutes ago, give bz another try if you don't mind :)

**Comment by Bheleu** [comment]
Did you update SimeonOnSecurity's pull request?
“Implement docker image CICD“
Thanks!

**Comment by Tkorrick** [comment]
> That issue should have been fixed as of 5 minutes ago, give bz another try if you don't mind :)

Ok Trying now - will let run overnight and see how it goes!

**Comment by Tkorrick** [comment]
Still not working for me. I have no issues on other pools as a check.

Here is a shot of the miner showing hashrate is still going but there are no shares. All miners running same version on same OS on same drivers.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/114526438/192689217-36514d71-091c-4fec-9565-0b1c23198b10.png">

Notice the share count
<img width="416" alt="image" src="https://user-images.githubusercontent.com/114526438/192689411-517179b6-71f6-48ba-8acf-97977b1c485a.png">

And Hashrate is reporting:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/114526438/192689502-c70061eb-b816-4745-af28-a4e6e966d82e.png">

**Comment by onemorebsmith** [comment]
Actually found the issue! Turns out there was a state that a miner could get in that you were connected so the bridge stopped sending but your socket was never closed. If you have 10 minutes or so today I'd appreciate it if you gave it another try @Tkorrick 

https://github.com/onemorebsmith/kaspa-stratum-bridge/commit/fb5cf9ae42ad7d3568f4ae3547f6b31aa5e882ce#diff-76c87456b045e8b97b0294a03970d8d5bd869a443afb928a6a0bbda5c028ca29L134

**Comment by Bheleu** [comment]
Update to latest stratum, see simeononsecurity pull request 12 days ago?

**Comment by Tkorrick** [comment]
@onemorebsmith Starting my miners up now. BTW did you fix the LOLminer 159a issue?

**Comment by onemorebsmith** [comment]
@Tkorrick I upgraded the kaspa node this morning to 12.7 to see if that addresses it. Lollideb said that no one else has reported the issue so I'm leaning on that being the issue

**Comment by onemorebsmith** [comment]
Not looking good. Ugh. Thanks anyways. I'll look closer later today

**Comment by Tkorrick** [comment]
@onemorebsmith  Sorry to say still have the issue with miners dropping to zero. Strange I don't have the issue with LOLMINER but do whit BZMINER. My rigs are mostly NVIDIA so can use SRBMINER.

**Comment by onemorebsmith** [comment]
@Tkorrick I switched all my rigs to bz to try and chase it down

**Comment by Tkorrick** [comment]
Strange right? I have 8 rigs. Maybe 1 will stay mining while the rest drop to zero shares. No error or rejected share messages in the miner. Thanks for looking into it!

**Comment by onemorebsmith** [comment]
Just hit a good block with lolminer 1.59a so I think that's good to go now at least.

**Comment by onemorebsmith** [comment]
All issues discussed so far should be addressed by https://github.com/onemorebsmith/kaspa-stratum-bridge/releases/tag/v1.1.4

**Comment by onemorebsmith** [comment]
@Tkorrick ⬆️

**Comment by onemorebsmith** [comment]
@Tkorrick did you get a chance to verify this fix worked for you?
